export const vehicleData = {
    marcas: {
      "Volvo": ["FH16", "FMX", "FM", "VNL", "VNM", "FMX 400", "FH", "FE"],
      "Mercedes": ["Actros", "Atego", "Unimog", "Sprinter", "M-Class", "Vito", "G-Class", "E-Class"],
      "MAN": ["TGX", "TGS", "TGL", "TGM", "Crafter", "TGE", "Lion's Coach"],
      "Scania": ["R-Series", "S-Series", "G-Series", "P-Series", "L-Series", "V8", "PGR", "Irizar"],
      "Ford": ["F-150", "F-250", "F-350", "Super Duty", "F-450", "F-550", "F-650", "F-750"],
      "Chevrolet": ["Silverado 1500", "Silverado 2500", "Colorado", "S10", "Tahoe", "Suburban", "Trailblazer", "Equinox"],
      "Ram": ["1500", "2500", "3500", "ProMaster", "ProMaster City", "Chassis Cab", "Power Wagon", "Laramie"],
      "Isuzu": ["N-Series", "F-Series", "Giga", "D-Max", "KB", "Elf", "Mu-X", "Trooper"],
      "Hino": ["300 Series", "500 Series", "700 Series", "J08E", "Dutro", "Motive", "Profia", "Titan"],
      "Mack": ["Granite", "Anthem", "Pinnacle", "TerraPro", "Titan", "LEU", "CHU", "MRU"],
      "Kenworth": ["T680", "T800", "W900", "T880", "C500", "T370", "T470", "K370"],
      "Peterbilt": ["579", "389", "567", "337", "348", "520", "536", "330", "567"],
      "Freightliner": ["Cascadia", "M2 106", "Columbia", "Business Class M2", "Coronado", "Sprinter", "Daimler Trucks", "FLD"],
      "International": ["LT", "ProStar", "Durastar", "MV", "Terrastar", "CV", "Star", "Tractor", "HX"],
      "DAF": ["XF", "CF", "LF", "CF Hybrid", "XG", "CF Electric", "CF LNG"],
      "Iveco": ["Stralis", "Eurocargo", "Daily", "Trakker", "S-Way", "EuroStar", "Powerstar", "Trakker Evolution"],
      "Fuso": ["Canter", "FJ", "FS", "Shogun", "Fighter", "Rosso", "Atego", "Super Great"],
      "Volkswagen": ["Crafter", "Transporter", "Amarok", "Caddy", "Touareg", "Atlas", "Multivan", "Passat"],
      "Toyota": ["Land Cruiser", "Hilux", "Tacoma", "Tundra", "Sequoia", "Fortuner", "4Runner", "Hiace"],
      "Nissan": ["Navara", "Titan", "Frontier", "Pathfinder", "Xterra", "Armada", "Murano", "Juke"],
      "GMC": ["Sierra 1500", "Sierra 2500", "Canyon", "Yukon", "Savana", "Terrain", "Acadia", "Sierra Denali"],
      "Chevy": ["Cheyenne", "Cavallero", "Blazer", "Impala", "Malibu", "Volt", "Spark", "Cruze"],
      "Honda": ["Ridgeline", "Pilot", "CR-V", "Accord", "Civic", "Element", "Odyssey", "Passport"],
      "Hyundai": ["Santa Fe", "Palisade", "Tucson", "Kona", "Elantra", "Ioniq", "Sonata", "Creta"],
      "Mazda": ["CX-5", "CX-9", "Mazda3", "Mazda6", "BT-50", "MX-5", "CX-30", "CX-3"],
      "Land Rover": ["Defender", "Discovery", "Range Rover", "Evoque", "Velar", "Sport", "Freelander", "Series III"],
      "Mitsubishi": ["L200", "Pajero", "Outlander", "Eclipse", "ASX", "Colt", "Mirage", "Lancer"],
      "Peugeot": ["Partner", "Boxer", "Expert", "208", "3008", "5008", "Traveller", "4007"],
      "Fiat": ["Ducato", "Scudo", "Doblo", "Panda", "Punto", "500X", "Tipo", "Fullback"],
      "Subaru": ["Outback", "Forester", "Impreza", "Legacy", "Ascent", "Crosstrek", "XV", "Tribeca"],
      "BMW": ["X5", "X7", "X3", "X1", "X6", "iX", "Z4", "M3", "M5", "M8"],
      "Audi": ["Q5", "Q7", "Q3", "Q8", "A4", "A3", "A6", "A7", "A8"],
      "Lexus": ["RX", "LX", "NX", "GX", "LS", "ES", "LC", "IS"],
      "Chrysler": ["Ram 1500", "Ram 2500", "Ram 3500", "Pacifica", "Voyager", "Chrysler 300", "Chrysler Aspen"],
      "Jeep": ["Cherokee", "Grand Cherokee", "Wrangler", "Gladiator", "Renegade", "Compass"],
      "Land_Rover": ["Discovery", "Range Rover", "Defender", "Sport", "Evoque", "Velar", "Freelander"]
    }as { [key: string]: string[] },
  };
  